language: java
cache:
  directories:
    - $HOME/.m2
matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: trusty
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
    - name: "Linux JDK11"
      os: linux
      dist: xenial
      jdk:
        - openjdk11
      env:
        - TRAVIS_DIST_NAME="xenial"
    - name: "Linux JDK13"
      os: linux
      dist: xenial
      jdk:
        - openjdk13
      env:
        - TRAVIS_DIST_NAME="xenial"
    - name: "MacOS JDK8"
      os: osx
      osx_image: xcode9.3
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="osx9"
    - name: "MacOS JDK11"
      os: osx
      osx_image: xcode10.1
      jdk:
        - openjdk11
      env:
        - TRAVIS_DIST_NAME="osx10"
    - name: "MacOS JDK13"
      os: osx
      osx_image: xcode10.1
      jdk:
        - openjdk13
      env:
        - TRAVIS_DIST_NAME="osx10"
before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install r; fi
  # to support exotic naming in osx like /usr/local/Cellar/r/3.5.2_2, no longer needed: - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then for l in `ls *_*`; do echo $l; l=`echo $l | cut -d: -f1`; ll=`echo $l | cut -d_ -f1`;ln -s $l $ll; done; fi;
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xvfb -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 ; sleep 3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [[ "$TRAVIS_DIST_NAME" == "trusty" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_DIST_NAME" == "xenial" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install r-recommended ant --allow-unauthenticated -y; fi
  - if [[ "$TRAVIS_DIST_NAME" == "osx10" ]]; then brew cask install homebrew/cask-versions/java11; export JAVA_HOME=$(/usr/libexec/java_home -v 11); fi
install: mvn install -DskipTests=true -Dgpg.skip=true
script: mvn clean test
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat `ls -r *.Rout | head -1`
