version: '{build}'
os: Windows Server 2012
platform: x64
init:
 - ps: |
        Get-Date
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
      Bootstrap
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5
  - cmd: SET R_HOME=C:\R
environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    USE_RTOOLS: false
    R_VERSION: release
test_script:
  - mvn clean test
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
  - C:\R\
on_failure:
  - 7z a failure.zip C:\projects\rsession
  - appveyor PushArtifact failure.zip
artifacts:
  - path: '**\*.log'
    name: Logs
  - path: '**\*.out'
    name: Logs
  - path: '**\*.fail'
    name: Logs
  - path: '**\*.Rout'
    name: Logs
  - path: '*_*.tar.gz'
    name: Bits
  - path: '*_*.zip'
    name: Bits
